### ISSUE TITLE
To-Do

### ISSUE THREAD

**Issue by DomAmato** [brinnLabs/Create2#1]
Need to add more abstractions to help flesh out the library
- [ ] A main update that takes sensor assignment arguments and sets flags when certain events are satisfied
- [ ] A separate sensor listener function to set and remove listeners for certain sensors
- [ ] Get flags returns all current flags, returns requested flag
- [ ] Set drive functions, turn 90 degrees left or right, 180, set by degree or radian etc...
- [ ] set max/min speed
